# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'First_Window_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_First_window(object):
    def setupUi(self, First_window):
        First_window.setObjectName("First_window")
        First_window.setWindowModality(QtCore.Qt.ApplicationModal)
        First_window.resize(523, 544)
        self.verticalLayoutWidget = QtWidgets.QWidget(First_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 10, 221, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RoomID_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.RoomID_lineEdit.setText("")
        self.RoomID_lineEdit.setObjectName("RoomID_lineEdit")
        self.verticalLayout.addWidget(self.RoomID_lineEdit)
        self.RmbReturn_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.RmbReturn_lineEdit.setText("")
        self.RmbReturn_lineEdit.setObjectName("RmbReturn_lineEdit")
        self.verticalLayout.addWidget(self.RmbReturn_lineEdit)
        self.Mdx_Price_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Mdx_Price_lineEdit.setText("")
        self.Mdx_Price_lineEdit.setObjectName("Mdx_Price_lineEdit")
        self.verticalLayout.addWidget(self.Mdx_Price_lineEdit)
        self.Mdx_Price_lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Mdx_Price_lineEdit_2.setText("")
        self.Mdx_Price_lineEdit_2.setObjectName("Mdx_Price_lineEdit_2")
        self.verticalLayout.addWidget(self.Mdx_Price_lineEdit_2)
        self.double_mdx_price_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.double_mdx_price_lineEdit.setText("")
        self.double_mdx_price_lineEdit.setObjectName("double_mdx_price_lineEdit")
        self.verticalLayout.addWidget(self.double_mdx_price_lineEdit)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.Mtl_price_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Mtl_price_lineEdit.setText("")
        self.Mtl_price_lineEdit.setObjectName("Mtl_price_lineEdit")
        self.verticalLayout.addWidget(self.Mtl_price_lineEdit)
        self.Mtl_price_lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Mtl_price_lineEdit_2.setText("")
        self.Mtl_price_lineEdit_2.setObjectName("Mtl_price_lineEdit_2")
        self.verticalLayout.addWidget(self.Mtl_price_lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.NextStep_pushButton = QtWidgets.QPushButton(First_window)
        self.NextStep_pushButton.setGeometry(QtCore.QRect(180, 490, 151, 31))
        self.NextStep_pushButton.setObjectName("NextStep_pushButton")

        self.retranslateUi(First_window)
        QtCore.QMetaObject.connectSlotsByName(First_window)

    def retranslateUi(self, First_window):
        _translate = QtCore.QCoreApplication.translate
        First_window.setWindowTitle(_translate("First_window", "登录"))
        self.RoomID_lineEdit.setPlaceholderText(_translate("First_window", "请输入房间号/必填"))
        self.RmbReturn_lineEdit.setPlaceholderText(_translate("First_window", "请输入返点率/可不填"))
        self.Mdx_Price_lineEdit.setPlaceholderText(_translate("First_window", "请输入迷迭香价格/可不填"))
        self.Mdx_Price_lineEdit_2.setPlaceholderText(_translate("First_window", "请输入小迷迭香价格/可不填"))
        self.double_mdx_price_lineEdit.setPlaceholderText(_translate("First_window", "请输入两倍迷迭香价格/可不填"))
        self.lineEdit_5.setPlaceholderText(_translate("First_window", "请输入三倍迷迭香价格/可不填"))
        self.Mtl_price_lineEdit.setPlaceholderText(_translate("First_window", "请输入摩天轮价格/可不填"))
        self.Mtl_price_lineEdit_2.setPlaceholderText(_translate("First_window", "请输入小摩天轮价格/可不填"))
        self.lineEdit.setPlaceholderText(_translate("First_window", "请输入两倍摩天轮价格/可不填"))
        self.lineEdit_2.setPlaceholderText(_translate("First_window", "请输入三倍摩天轮价格/可不填"))
        self.lineEdit_3.setPlaceholderText(_translate("First_window", "请输入梦幻热气球价格/可不填"))
        self.lineEdit_4.setPlaceholderText(_translate("First_window", "请输入星际战舰价格/可不填"))
        self.NextStep_pushButton.setText(_translate("First_window", "下一步"))
