# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Monitor_player.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Monitor_players(object):
    def setupUi(self, Monitor_players):
        Monitor_players.setObjectName("Monitor_players")
        Monitor_players.resize(694, 665)
        self.verticalLayoutWidget = QtWidgets.QWidget(Monitor_players)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 171, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.label = QtWidgets.QLabel(Monitor_players)
        self.label.setGeometry(QtCore.QRect(10, 0, 169, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Monitor_players)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(190, 40, 61, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_2.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_2.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_2.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_2.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_2.addWidget(self.lineEdit_10)
        self.label_2 = QtWidgets.QLabel(Monitor_players)
        self.label_2.setGeometry(QtCore.QRect(180, 0, 81, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(Monitor_players)
        self.textBrowser.setGeometry(QtCore.QRect(10, 370, 671, 281))
        font = QtGui.QFont()
        font.setFamily("YaHei Consolas Hybrid")
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(Monitor_players)
        self.pushButton.setGeometry(QtCore.QRect(260, 110, 41, 111))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Monitor_players)
        self.label_3.setGeometry(QtCore.QRect(430, 5, 121, 21))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Monitor_players)
        self.label_4.setGeometry(QtCore.QRect(430, 185, 121, 21))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Monitor_players)
        self.label_5.setGeometry(QtCore.QRect(70, 330, 121, 21))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Monitor_players)
        self.textBrowser_2.setGeometry(QtCore.QRect(310, 30, 371, 151))
        font = QtGui.QFont()
        font.setFamily("YaHei Consolas Hybrid")
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Monitor_players)
        self.textBrowser_3.setGeometry(QtCore.QRect(310, 210, 371, 151))
        font = QtGui.QFont()
        font.setFamily("YaHei Consolas Hybrid")
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setObjectName("textBrowser_3")

        self.retranslateUi(Monitor_players)
        QtCore.QMetaObject.connectSlotsByName(Monitor_players)

    def retranslateUi(self, Monitor_players):
        _translate = QtCore.QCoreApplication.translate
        Monitor_players.setWindowTitle(_translate("Monitor_players", "玩家监控"))
        self.label.setText(_translate("Monitor_players", "请输入需要监控玩家ID"))
        self.label_2.setText(_translate("Monitor_players", "折扣率"))
        self.pushButton.setText(_translate("Monitor_players", "确定"))
        self.label_3.setText(_translate("Monitor_players", "当前红包"))
        self.label_4.setText(_translate("Monitor_players", "总计"))
        self.label_5.setText(_translate("Monitor_players", "每轮记录"))

