# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Third_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Modifiy_gift_price(object):
    def setupUi(self, Modifiy_gift_price):
        Modifiy_gift_price.setObjectName("Modifiy_gift_price")
        Modifiy_gift_price.resize(202, 453)
        self.verticalLayoutWidget = QtWidgets.QWidget(Modifiy_gift_price)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 10, 101, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout.addWidget(self.lineEdit_10)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout.addWidget(self.lineEdit_9)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout.addWidget(self.lineEdit_11)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout.addWidget(self.lineEdit_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout.addWidget(self.lineEdit_8)
        self.pushButton = QtWidgets.QPushButton(Modifiy_gift_price)
        self.pushButton.setGeometry(QtCore.QRect(50, 410, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Modifiy_gift_price)
        QtCore.QMetaObject.connectSlotsByName(Modifiy_gift_price)

    def retranslateUi(self, Modifiy_gift_price):
        _translate = QtCore.QCoreApplication.translate
        Modifiy_gift_price.setWindowTitle(_translate("Modifiy_gift_price", "Form"))
        self.lineEdit_4.setPlaceholderText(_translate("Modifiy_gift_price", "超跑派对卡"))
        self.lineEdit_2.setPlaceholderText(_translate("Modifiy_gift_price", "迷迭香价格"))
        self.lineEdit_10.setPlaceholderText(_translate("Modifiy_gift_price", "小迷迭香价格"))
        self.lineEdit.setPlaceholderText(_translate("Modifiy_gift_price", "两倍香价格"))
        self.lineEdit_9.setPlaceholderText(_translate("Modifiy_gift_price", "三倍香价格"))
        self.lineEdit_3.setPlaceholderText(_translate("Modifiy_gift_price", "摩天轮价格"))
        self.lineEdit_11.setPlaceholderText(_translate("Modifiy_gift_price", "小摩天轮价格"))
        self.lineEdit_6.setPlaceholderText(_translate("Modifiy_gift_price", "两倍轮子价格"))
        self.lineEdit_5.setPlaceholderText(_translate("Modifiy_gift_price", "三倍轮子价格"))
        self.lineEdit_7.setPlaceholderText(_translate("Modifiy_gift_price", "热气球价格"))
        self.lineEdit_8.setPlaceholderText(_translate("Modifiy_gift_price", "星际战舰价格"))
        self.pushButton.setText(_translate("Modifiy_gift_price", "确定"))
